// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnkpgB221tHZJt_cfJ-WN9Bwb6BLBSs8o',
    appId: '1:596606544320:web:premier',
    messagingSenderId: '596606544320',
    projectId: 'premier-laundry-dcef2',
    storageBucket: 'premier-laundry-dcef2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkpgB221tHZJt_cfJ-WN9Bwb6BLBSs8o',
    appId: '1:596606544320:android:1844f8c184f412d831c025',
    messagingSenderId: '596606544320',
    projectId: 'premier-laundry-dcef2',
    storageBucket: 'premier-laundry-dcef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32I_Iq8Rd9jAPP3LKEKGT6UY3JYdgw5w',
    appId: '1:596606544320:ios:cf94d4f833a20fed31c025',
    messagingSenderId: '596606544320',
    projectId: 'premier-laundry-dcef2',
    storageBucket: 'premier-laundry-dcef2.firebasestorage.app',
    iosBundleId: 'com.premierlaundry.app',
  );
}
